/**
 * useReportsLive — bridge live `batchAutopilotRuns` documents into the redesign's `ReportCardData` shape.
 *
 * Backend Sprint Step 1. Wire path:
 *   convex/domains/operations/batchAutopilot/queries.ts:getRecentRuns
 *     → derive ReportCardData[] (id, entity, kind, status, description, sources, claims, followUps, updatedAt)
 *
 * When the user is unauthenticated or has no runs yet, the hook returns the fixture array so
 * the redesign route still renders for guest visitors / dogfood demos.
 */

import { useQuery } from "convex/react";
import { api } from "../../../../convex/_generated/api";
import { reports as fixtureReports, type ReportCardData } from "../fixtures";

interface BatchAutopilotRun {
  _id: string;
  status: string;
  startedAt: number;
  completedAt?: number;
  briefDocumentId?: string;
  briefMarkdown?: string;
  deltaSummary?: string;
  feedItemsCount: number;
  signalsCount: number;
  narrativeEventsCount: number;
  plannedActions?: Array<{ description: string; status: string }>;
}

function deriveEntity(run: BatchAutopilotRun): string {
  // First non-empty markdown heading wins; fallback to "Operator brief"
  const md = run.briefMarkdown ?? run.deltaSummary ?? "";
  const m = md.match(/^#+\s+(.+)$/m);
  if (m) return m[1].slice(0, 64).trim();
  return "Operator brief";
}

function deriveStatus(run: BatchAutopilotRun): ReportCardData["status"] {
  switch (run.status) {
    case "completed": return "verified";
    case "failed": return "review";
    case "delivering":
    case "generating_brief":
    case "summarizing":
    case "collecting": return "watching";
    default: return "watching";
  }
}

function timeAgo(at: number): string {
  const delta = Math.max(0, Date.now() - at);
  const m = Math.floor(delta / 60_000);
  if (m < 1) return "just now";
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  const d = Math.floor(h / 24);
  return `${d}d ago`;
}

function runToReport(run: BatchAutopilotRun): ReportCardData {
  const sources = run.feedItemsCount + run.signalsCount + run.narrativeEventsCount;
  const claims = run.plannedActions?.length ?? 0;
  const description = (run.deltaSummary ?? run.briefMarkdown ?? "Brief generated by batch autopilot.")
    .replace(/^#+\s+.+\n/m, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 220);
  return {
    id: run._id,
    entity: deriveEntity(run),
    kind: "Brief",
    status: deriveStatus(run),
    description,
    sources,
    claims,
    followUps: 0,
    updatedAt: timeAgo(run.completedAt ?? run.startedAt),
  };
}

export interface UseReportsLiveResult {
  reports: ReportCardData[];
  /** True when live Convex data is being shown; false when falling back to fixtures. */
  isLive: boolean;
  /** True while the query is loading for the first time. */
  isLoading: boolean;
}

export function useReportsLive(): UseReportsLiveResult {
  // Cast through unknown because the api shape may not match exactly until codegen runs.
  const liveRuns = useQuery(
    (api as unknown as { domains: { operations: { batchAutopilot: { queries: { getRecentRuns: unknown } } } } })
      .domains.operations.batchAutopilot.queries.getRecentRuns as Parameters<typeof useQuery>[0],
    { limit: 50 } as Parameters<typeof useQuery>[1],
  ) as BatchAutopilotRun[] | undefined;

  if (liveRuns === undefined) {
    return { reports: fixtureReports, isLive: false, isLoading: true };
  }
  if (liveRuns.length === 0) {
    return { reports: fixtureReports, isLive: false, isLoading: false };
  }
  return {
    reports: liveRuns.map(runToReport),
    isLive: true,
    isLoading: false,
  };
}
